### PR TITLE
use auto-uds multi branch

### PR DESCRIPTION
**Pull request by nyurik**
This PR uses the reworked auto-uds, now published as automotive_diag, which migrates many OBD and KWP constants

### CODE REVIEW

**Comment by rnd-ash** [comment]
Maybe we can create separate crates for this? Or rename auto_uds? I don't like the idea of the crate being called UDS but implementing other diagnostic protocols....


Also sidenote. The kwp specification may be best left out as it only appears to conform to what Daimler and jeep use. Other OEMs also use kwp but use their own SIDS and PIDS

**Comment by nyurik** [comment]
I think maintaining multiple crates will be a bit painful -- I would prefer a monorepo, but I do agree that `auto_uds` is a bad name for that... Naming ideas:
* `auto-diag`
* `automotive-diag`
* `automotive_diag` -- my personal pref - note that underscore tends to create fewer problems overall
* ...?

The structure of the code will be identical to the `multi` branch in the `auto_uds`:

```
/src
  /uds
  /kwp2k
  /obd2
```

The "non-standard" kwp could be placed in some subdir i guess, e.g. `/kwp2k/daimler` vs `kwp2k/foobar` ?

**Comment by rnd-ash** [comment]
Sure! I'm a fan of `automotive_diag`.

I agree with your structure too, let's go ahead with that then

**Comment by nyurik** [comment]
ok, give me a sec, will have something in a few min

**Comment by nyurik** [comment]
done, re-published the multi as the 0.1.0 version

**Comment by nyurik** [comment]
@rnd-ash I had a few issues when migrating your code, and I'm not certain if those are bugs or what:
* https://github.com/nyurik/automotive_diag/blob/7678163a06132e9660b704c001258ff529f5e5d0/src/obd2/data_pids.rs#L72-L73
* https://github.com/nyurik/automotive_diag/blob/7678163a06132e9660b704c001258ff529f5e5d0/src/obd2/errors.rs#L37-L38
* https://github.com/nyurik/automotive_diag/blob/7678163a06132e9660b704c001258ff529f5e5d0/src/obd2/fuel_system_status.rs#L12

Also, a few other things:
* should the `ObdEnumValue` be migrated too? I am not certain I understood how it gets (de-)serialized
* kwp2000/DTCRange?
* kwp2000/routine (several enums)
* ObdUnitType?
* Is it ok to name things `KwpCommand` instead of `Kwp2kCommand`, while keeping it in the `kwp2000` namespace? Or is 2k/2000 important?
* Same for Obd vs Obd2
* Can we rename the OBD-II services? It seems weird to have the code inside the service name, e.g. `Service09Pid` - doesn't make any sense tbh

Probably a few other ones too, but not certain

**Comment by nyurik** [comment]
@rnd-ash hi, let me know WRT above, or possibly submit a PR for the automotive_diag? thx!

**Comment by rnd-ash** [comment]
Hey, I'll review this tomorrow. I'm pretty packed today. I'd recommend changing the crate to automotive_diag tho!

**Comment by nyurik** [comment]
Thx, no rush. I'm not sure what you mean by changing the create - it has already been renamed and published

**Comment by rnd-ash** [comment]
Awesome. I'm happy with this. Lets merge!

**Comment by nyurik** [comment]
Thx for emerging. What do you think about the questions above?

**Comment by rnd-ash** [comment]
hey @nyurik ,

Firstly, the links you provided are invalid, so I cannot check what you mean by 'bugs'.

Now regarding your points you raised.

1-4. I think for now we should keep the enums in the ecu_diagnostics crate. Certain things like the KWP routine identifiers are not exactly 'global', as every OEM may have a different routine ID. We can look back at this at a later date once the unified branch is merged.

5. Yes, we should keep the enums called 'kwp' rather than 'kwp2000'. KWP2000 is the official specification name, but it is abbreviated to 'kwp', especially when also referring to its lower layer that runs over LIN for K-Line diagnostics rather than CAN (To be implemented at a later date).  

6. I'd agree this maybe should be called 'OBD2' rather than 'OBD'
7. Yes we can rename this too

**Comment by nyurik** [comment]
@rnd-ash I fixed the links (they got merged and the original branch was deleted). Look for "FIXME" next to the linked code.

In the obd2 namespace, i have `Obd2Command`, `Obd2Error`, but `ObdStandard` (all other enums are non-obd prefixed). Should the standard also be `Obd2Standard` ? Seems weird because that enum contains obd2 and others. On the other hand, it is weird to have both the `ObdStandard` enum in the same namespace as all Obd2-specific enums.  Not certain if those should be logically separate? I have no domain knowledge on OBD.

What would the names of the `Service<code>` be?

Thx!

**Comment by rnd-ash** [comment]
Hey i saw the FIXMEs. I will work on them at a later date.

I think its best to rename the ObdStandard to Obd2Standard. Since Obd is also a protocol (Which I don't know much about). I was going to keep the namepsace of ObdStandard as Obd2 is a successor to Obd, so maybe i might add Obd at a later date to the crate.

**Comment by nyurik** [comment]
Sounds good, thx, lets iterate on it for the next version

**Pull request merged**
